spring:
  application:
    name: auth-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 0

app:
  jwt:
    secret: c10y7kWL8r5BXgmRK1H1BylY6Ne90wcIITPUnRNye83NNl0NwSJ9v2qJuXqztzse
    tokenExpirationMsec: 86400000
