spring:
  application:
    name: auth-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 0
app:
  jwt:
    secret: ${JWT_SECRET}
    tokenExpirationMsec: ${JWT_EXPIRATION}
