version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    networks:
      - backend

networks:
  backend:
