spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/v1/tickets/**
          filters:
            - RewritePath=/api/v1/tickets/(?<segment>.*), /api/v1/tickets/$\{segment}
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - RewritePath=/api/v1/accounts/(?<segment>.*),/api/v1/accounts/$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*),/api/v1/auth/$\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: false
    fetch-registry: true
