spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/v1/tickets/**
          filters:
            - RewritePath=/api/v1/tickets/(?<path>.*), /$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: false
    fetch-registry: true
